# Site settings
title: "A Y C H O M E"
description: 'Read AYCHOME in plain text online.

The AYCHOME is a fresh version of accessing AYCH inc services and products. This is a manual, step-by-step guide, towards management and software products. It is meant to be practical. It is meant for use.'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aychome.github.io" # the base hostname & protocol for your site
github_username: Creditbox
github_url:  https://github.com/aychome/aychome.io
permalink: pretty
exlude:
  - css/style.styl
  - Gemfile
  - Gemfile.lock
  - README.md
  - working/

# Build settings
markdown: kramdown
