# Site settings
title: "Peacera 2020"
description: 'Read Peacera in Plain English online.

The Peacera is a fresh version for Mindfulness practice which is sourced from Vipassana meditation practice. Repeat, practice. This is a meditation manual, a nuts-and-bolts, step-by-step guide to Insight meditation. It is meant to be practical. It is meant for use.'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://peacera.github.io" # the base hostname & protocol for your site
github_username: Creditbox
github_url:  https://github.com/peacera/peacera.io
permalink: pretty
exlude:
  - css/style.styl
  - Gemfile
  - Gemfile.lock
  - README.md
  - working/

# Build settings
markdown: kramdown
