# Site settings
title: "Mindfulness in Plain English"
description: 'Read Mindfulness in Plain English online, a practical guide to Vipassana meditation.

The subject of this book is Vipassana meditation practice. Repeat, practice. This is a meditation manual, a nuts-and-bolts, step-by-step guide to Insight meditation. It is meant to be practical. It is meant for use.'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mindfulness-in-plain-english.github.io" # the base hostname & protocol for your site
github_username: Soreine
permalink: pretty
exlude:
  - css/style.styl
  - Gemfile
  - Gemfile.lock
  - README.md
  - working/

# Build settings
markdown: kramdown
